/* Generated by cbindgen — do not edit */

#ifndef PHEMY_CORE_H
#define PHEMY_CORE_H

/* This file is auto-generated. Do not modify. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Initialize phemy-core with a data directory path.
 * Must be called before any other function.
 * Returns true on success, true (no-op) on subsequent calls.
 */
bool phemy_init(const char *data_dir);

/**
 * Get current settings as JSON string.
 * Caller must free the returned string with phemy_free_string().
 */
char *phemy_get_settings(void);

/**
 * Save settings from a JSON string. Returns true on success.
 */
bool phemy_save_settings(const char *json);

/**
 * Reset settings to defaults and return new settings as JSON.
 * Caller must free the returned string with phemy_free_string().
 */
char *phemy_reset_settings(void);

/**
 * List audio input devices as JSON array.
 * Caller must free the returned string with phemy_free_string().
 */
char *phemy_list_audio_devices(void);

/**
 * Start recording. `device` may be null for default device.
 * `mic_cb` is a C function pointer called on the audio thread with (rms, peak), or null.
 */
bool phemy_start_recording(const char *device, void (*mic_cb)(float, float));

/**
 * Stop recording and return JSON with samples info.
 * Caller must free the returned string with phemy_free_string().
 */
char *phemy_stop_recording(void);

/**
 * Stop recording, transcribe, optimize, save to history, and return JSON result.
 * Always returns JSON (never null). On success: { "raw_transcript": "...", "optimized_prompt": "...", "mode": "...", "duration_secs": ... }
 * On error: { "error": "description of what went wrong" }
 * Caller must free the returned string with phemy_free_string().
 */
char *phemy_stop_and_process(void);

/**
 * Check if currently recording.
 */
bool phemy_get_recording_state(void);

/**
 * Transcribe audio samples. Returns JSON result.
 * Caller must free the returned string with phemy_free_string().
 */
char *phemy_transcribe(const float *samples, uintptr_t len, uint32_t rate);

/**
 * List available whisper models as JSON array.
 * Caller must free the returned string with phemy_free_string().
 */
char *phemy_list_whisper_models(void);

/**
 * Download a whisper model by name. Blocking.
 */
bool phemy_download_whisper_model(const char *name);

/**
 * Get download progress as JSON, or null if not downloading.
 * Caller must free the returned string with phemy_free_string().
 */
char *phemy_get_download_progress(void);

/**
 * Optimize a transcript into a polished prompt. Returns JSON.
 * Caller must free the returned string with phemy_free_string().
 */
char *phemy_optimize_prompt(const char *transcript);

/**
 * List available local LLM models as JSON array.
 * Caller must free the returned string with phemy_free_string().
 */
char *phemy_list_llm_models(void);

/**
 * Download a local LLM model by name. Blocking.
 */
bool phemy_download_llm_model(const char *name);

/**
 * Get LLM model download progress as JSON, or null if not downloading.
 * Caller must free the returned string with phemy_free_string().
 */
char *phemy_get_llm_download_progress(void);

/**
 * Delete a downloaded whisper model by name. Returns true on success.
 */
bool phemy_delete_whisper_model(const char *name);

/**
 * Delete a downloaded LLM model by name. Returns true on success.
 */
bool phemy_delete_llm_model(const char *name);

/**
 * Get history entries as JSON array.
 * Caller must free the returned string with phemy_free_string().
 */
char *phemy_get_history(int32_t limit, int32_t offset);

/**
 * Delete a history entry by ID. Returns true on success.
 */
bool phemy_delete_history_entry(const char *id);

/**
 * Clear all history. Returns true on success.
 */
bool phemy_clear_history(void);

/**
 * Paste text into the focused application.
 */
bool phemy_paste_text(const char *text);

/**
 * Free a string returned by any phemy_* function.
 */
void phemy_free_string(char *ptr);

#endif  /* PHEMY_CORE_H */
